# read vault secret
- hosts: localhost
  tasks:
    - name: read vault value
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/another:foo') }}"

# write vault secret
- hosts: localhost
  roles:
    - ansible-modules-hashivault
  tasks:
    - name: write value to vault
      hashivault_secret:
        secret: some_secret
        data:
          foo: foe
          fie: fum
